export const BIOGRAPHY = [
    {
      id: 0,
      name: 'Biography',
      image: '/assets/images/cactus2.jpg',
      imageB: '/assets/images/bioPic4.jpg',
      featured: true,
      description: 'Click here to view my biography.  New father, proud husband, and outdoor enthusiast!',
      paragraph: 'Hello.  I’m a web developer. I spend most of my day, every day, pouring over mostly JavaScript code, HTML, CSS, arrays of various JS libraries/tools and information other community members have posted online. I build websites and mobile apps that are intuitive,  fun to use, and I do it well.\n\nMy goal is to be constantly learning, whether as an autodidact or student.  I stay current on the latest technology trends and I implement what I learn into my projects.  In six weeks, I will be full-stack JavaScript certified, and then I plan on enrolling in a few other certifications involving AWS and AI.\n\n\nProfessional Bio~~\nAt the moment, I am fortifying my front-end JavaScript knowledge in creating React Native mobile apps.  Currently, I’m working on two mobile apps; Ristorante Con Fusion, and my personal portfolio. Both apps are extensions of working React.js web apps that I’ve made and can be seen/navigated at www.ericsyme.com.\n\nRistorante Con Fusion is a mock-up of a restaurant that has multiple pages that features their tops dishes, corporate leaders, history, feedback, and has the ability to login as an employee.  Soon, a back-end element will be added as well.\n\n My personal portfolio page is also one of my main projects, which showcases UX and web design.  You can find my current projects, certifications, and biography as well.\n\n\nPersonal Bio~~\nMy current job is the best job I’ve ever had; stay-at-home parent for my now thirteen-month-old daughter.  She is my world, and she is full of happiness and energy.  Watching her wonder over the world brings my wife and I such happiness.\n\nWe bought our first home a few years ago, and love living in Kitsap County.  We were such big city-rats, but now I LOVE being more rural. I can see a farmhouse in our future, with some chickens maybe.\n\nI also can’t wait to get back into pottery! One of the things I learned I have a knack for is the potter’s wheel (I had an internship at NW Pottery).  After I get a wheel and kiln EVERYONE I know will get beer mugs for the holidays! Ha ha ha ha!'
    }
  ];